{
 "title": "Coreum Dashboard",
 "description": "Dashboard for Coreum",
 "tags": [
  "Blockchain",
  "Cosmos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cosmos", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cometbft_consensus_height, chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cometbft_consensus_height{chain_id=~\"$chain_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain_id=~\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{chain_id=~\"$chain_id\", instance=~\"$instance\"}[5m]) / rate(cometbft_consensus_block_interval_seconds_count{chain_id=~\"$chain_id\", instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=~\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "cometbft_consensus_missing_validators_power{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "cometbft_consensus_byzantine_validators_power{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "$instance metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cometbft_p2p_peers{chain_id=~\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Unconfirmed Transactions",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "cometbft_mempool_size{chain_id=~\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Failed Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_mempool_failed_txs{chain_id=~\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Recheck Times",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_mempool_recheck_times{chain_id=~\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Block Size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cometbft_consensus_block_size_bytes{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
       "legendFormat": "Block Size"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cometbft_consensus_num_txs{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
       "legendFormat": "Transactions"
      }
     ]
    },
    {
     "title": "Mempool Size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cometbft_mempool_size{chain_id=~\"$chain_id\",instance=~\"$instance\",job=\"cosmos\"}",
       "legendFormat": "Mempool Size"
      }
     ]
    },
    {
     "title": "Mempool Size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cometbft_mempool_size{chain_id=~\"$chain_id\",instance=~\"$instance\",job=\"cosmos\"}",
       "legendFormat": "Mempool Size"
      }
     ]
    },
    {
     "title": "Total Network Input",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cometbft_p2p_peer_receive_bytes_total{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total Network Output",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cometbft_p2p_peer_send_bytes_total{chain_id=~\"$chain_id\", instance=~\"$instance\"}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Min Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "min_gas_price", "legendFormat": "Min gas price" }
   ]
  },
  {
   "title": "Deterministic gas factor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deterministic_gas_factor{job=\"cosmos\",quantile=\"0.9\"}",
     "legendFormat": "{{msg_name}}"
    },
    {}
   ]
  },
  {
   "title": "Deterministic gas factor exceed expected max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deterministic_gas_factor_exceed_expected_max{job=\"cosmos\",quantile=\"0.9\"}",
     "legendFormat": "{{msg_name}}"
    },
    {}
   ]
  },
  {
   "title": "Deterministic gas exceed fuse gas multiplier",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deterministic_gas_exceed_fuse_gas_multiplier{job=\"cosmos\",quantile=\"0.9\"}",
     "legendFormat": "{{msg_name}}"
    },
    {}
   ]
  }
 ]
}